package com.hp.thylacine;

public enum Type {
  UNKNOWN, ILLEGAL, MISSING,
  INT, FLOAT, STRING, PAD, WELL, REGION, RECT, SEGMENT, PATH,
  BOOL, 
  VOLUME, TEMP, TIME, FREQ,
  HDELTA, VDELTA, DELTA2D, ROWS, COLS, PADS,
  OPCALL
}
