from __future__ import annotations
from enum import Enum, auto
from os import PathLike
from typing import Optional

class ErrorCode(Enum):
    ErrorSuccess = auto()
    ErrorFailure = auto()
    ErrorFailureHardware = auto()
    ErrorFailureToOpenFile = auto()
    ErrorFailureSystem = auto()
    
class BoardId(Enum):
    Unknown = auto()
    Wallaby = auto()
    
    
class Electrode:
    class ElectrodeState(Enum):
        Off = auto()
        On = auto()
        Unknown = auto()
        
    def GetName(self) -> str: ...
    def GetCoordinatesList(self) -> list[tuple[int, int]]: ...
    def GetCurrentState(self) -> ElectrodeState: ...
    def GetTargetState(self) -> ElectrodeState: ...
    def SetTargetState(self, electrodeState: ElectrodeState) -> ErrorCode: ... # @UnusedVariable
    def GetHeaters(self) -> list[str]: ...
    def GetDataBufferIndex(self) -> int: ...
    
class Heater:
    class HeaterType(Enum):
        Paddle = auto()
        TSR = auto()
        Unknown = auto()
        
    class HeaterState(Enum):
        Off = auto()
        On = auto()
        Unknown = auto()
        
    class HeaterStatus(Enum):
        Warming = auto()
        Cooling = auto()
        Unknown = auto()
        
    class Status:
        def GetHeaterState(self) -> Heater.HeaterState: ...
        def GetCurrentTemperature(self) -> float: ...
        def GetTargetTemperature(self) -> float: ...
        def GetEtaInMilliseconds(self) -> int: ...
        
    def GetName(self) -> str: ...
    def GetStatus(self) -> Status: ...
    def GetCurrentState(self) -> HeaterState: ...
    def GetTargetState(self) -> HeaterState: ...
    def GetCurrentTemperature(self) -> float: ...
    def GetTargetTemperature(self) -> float: ...
    def SetTargetTemperature(self, targetTemperature: float) -> ErrorCode: ... # @UnusedVariable
    def GetElectrodeNames(self) -> list[str]: ...
    def GetElectrodes(self) -> list[Electrode]: ...
    
class Board:
    def test(self) -> str: ...
    @classmethod
    def Find(cls, boardID: BoardId, *, # @UnusedVariable
             dll_dir: Optional[PathLike] = None, # @UnusedVariable
             config_dir: Optional[PathLike] = None) -> Board: ... # @UnusedVariable
    def GetBoardId(self) -> BoardId: ...
    def GetBoardRows(self) -> int: ...
    def GetBoardColumns(self) -> int: ...
    def GetElectrodes(self) -> list[Electrode]: ...
    def ElectrodeAt(self, x: int, y: int) -> Optional[Electrode]: ... # @UnusedVariable
    def ElectrodeNamed(self, name: str) -> Optional[Electrode]: ... # @UnusedVariable
    def DumpElectrodes(self) -> ErrorCode: ...
    def GetHeaters(self) -> list[Heater]: ...
    def DumpHeaters(self) -> ErrorCode: ...
    def MakeItSo(self) -> ErrorCode: ...
