name: mypy

on: [push, pull_request]

jobs:
  Python:
    runs-on: rnd-it-ubuntu
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Setup Dependencies
        run: |
          pip install mypy types-requests
          pip install -r mpam/requirements.txt

      - name: Run mypy
        run:
          mypy
          --follow-imports=silent
          --ignore-missing-imports
          --show-column-numbers
          --show-error-codes
          --strict-equality
          --warn-redundant-casts
          --warn-return-any
          --warn-unreachable
          --disallow-incomplete-defs
          --disallow-untyped-defs
          --no-implicit-optional
          mpam/{src,tools,dev-tools}
